Fix htole64 and le64toh missing on non-linux platforms
starkware-libs/crypto-cpp pull request #12
Opened 2022-08-15 09:17 UTC by Solpatium

Split from https://github.com/starkware-libs/crypto-cpp/pull/11

2022-08-16 08:27 UTC, ilyalesokhin-starkware commented on src/starkware/crypto/ffi/portable_endian.h
> +#ifndef STARKWARE_CRYPTO_FFI_PORTABLE_ENDIAN_H_
Did you strip the license header?

2022-08-16 09:25 UTC, ilyalesokhin-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/crypto-cpp/12)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @Solpatium)

___
*[`src/starkware/crypto/ffi/utils.cc` line 1 at r1](https://reviewable.io/reviews/starkware-libs/crypto-cpp/12#-N9_yCEs-8wJ43oMyLwf:-N9_yCEs-8wJ43oMyLwg:bm8izls) ([raw file](https://github.com/starkware-libs/crypto-cpp/blob/91339de7414a7d4fc2999675b5d5fcae746bbb6a/src/starkware/crypto/ffi/utils.cc#L1)):*
> ```cpp
> #include <endian.h>
> ```

This should be removed now, right?



_Code quote:_
```cpp
#include <endian.h>
```


<!-- Sent from Reviewable.io -->

2022-09-08 11:03 UTC, Solpatium commented on src/starkware/crypto/ffi/portable_endian.h
> +#ifndef STARKWARE_CRYPTO_FFI_PORTABLE_ENDIAN_H_
Yes, I strip it from https://github.com/sahlberg/libsmb2/blob/master/include/portable-endian.h since author placed in public domain.

2022-09-08 11:05 UTC, Solpatium commented
Good catch, I missed it after the split from the initial PR. Sorry 😅

2022-09-08 13:17 UTC, ilyalesokhin-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/crypto-cpp/12#-:-NBSEo93EweZ2qExY5Qa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Solpatium)



<!-- Sent from Reviewable.io -->

2022-09-08 13:17 UTC, merged